services:
  server:
    build:
      context: .
    volumes:
       - /usr/share/coolify/services/kutt-click/db:/bridgeitclick/db
       - custom:/kutt/custom
    environment:
      DB_FILENAME: "/var/lib/kutt/data"
      SITE_NAME: "BridgeIt Click"
      DEFAULT_DOMAIN: "click.bridgeit-app.fr"
      JWT_SECRET: "your_jwt_secret_here"
      MAIL_ENABLED: false
      MAIL_HOST:
      MAIL_PORT: 465
      MAIL_SECURE: true
      MAIL_USER: 
      MAIL_FROM: 
      MAIL_PASSWORD: 

    ports:
      - 3000:3000
volumes:
  custom: